# Generated by Django 5.1.4 on 2024-12-18 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_question_answer_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.FloatField(default=14.01572999025127)),
                ('oib_score', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], default=2)),
                ('programming_score', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], default=2)),
                ('os_security_score', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], default=2)),
                ('direction_comment', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
